version: '3'

services:
  mongo:
    image: mongo:6.0.1
    container_name: database
    restart: always
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - ./mongo/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  node:
    image: node:alpine3.16
    container_name: backend
    working_dir: /usr/src/app
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src/app
    tty: true
    ports:
      - 3000:3000
 
networks:
  app-network:
    driver: bridge
  